spring:
  profiles:
    active: default
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.9.223:3306/zlikun?characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: ablejava
    name: zlikun
    schema: classpath:script/schema.sql
    data: classpath:script/data.sql
    sql-script-encoding: UTF-8
    initialize: false
    # https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_DruidDataSource%E5%8F%82%E8%80%83%E9%85%8D%E7%BD%AE
    # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      # 初始连接数
      initial-size: 10
      # 最大连接数
      max-active: 50
      # 最小连接数
      min-idle: 10
      # 连接等待超时时间，单位：毫秒
      max-wait: 30000
      # 查询超时时间，单位：毫秒
      query-timeout: 1500
      # 事务查询超时时间，单位：毫秒
      transaction-query-timeout: 1500
      # 登录超时时间(干嘛用的？第一次连接时登录的超时时间么？)
      login-timeout: 3000
      # 校验连接有效性查询SQL
      validation-query: SELECT 1 FROM DUAL
      # 校验连接超时时间，单位：毫秒
      validation-query-timeout: 1000
      # 是否在从连接池中取得连接时校验
      test-on-borrow: false
      # 是否在归还连接到连接池时校验
      test-on-return: false
      # 是否在连接空闲时校验
      test-while-idle: true
      # 检测需要关闭空闲连接间隔时间，单位：毫秒
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存时间（空闲状态），单位：毫秒
      min-evictable-idle-time-millis: 300000
      # 用于Oracle优化时使用，MySQL时禁用
      pool-prepared-statements: false
      # 配置监控拦截的过滤器()
      filters: stat,wall,slf4j
      # https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
      # 监控配置：WebStatFilter
      # https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_%E9%85%8D%E7%BD%AEWebStatFilter
      web-stat-filter:
        enabled: true
        # 需要拦截的请求
        url-pattern: /
        # 排除不需要拦截的请求
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        # 是否打开会话统计功能
        session-stat-enable: true
        # 统计的会话最大个数，默认：1000个
        session-stat-max-count: 10
        # 指定当前session中的用户名(登录用户在session中的名称键)
        principal-session-name: user.name
        # 与session类似，取cookie中的键
        principal-cookie-name: user.name
        # 是否监控单个url调用的sql列表
        profile-enable: true
      # 监控配置：StatViewServlet
      # https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
      stat-view-servlet:
        enabled: true
        # 监控请求入口
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        # 口令、密码
        login-username: root
        login-password: root
        # deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝
        deny: "192.168.9.223"
        allow: "127.0.0.1"
      # Spring监控配置
      aop-patterns:
        - com.zlikun.spring.controller.*
  mvc:
    favicon:
      enabled: false
server:
  port: 80