logging:
  level:
    root: info
    org.springframework.web.servlet: warn
    org.springframework.boot.web.servlet: warn
    org.springframework.boot.actuate.endpoint: warn
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
server:
  port: 80
  session:
    cookie:
      name: ZID
      http-only: true
      path: /
      domain: localhost
      max-age: -1
    timeout: 1800
spring:
  profiles:
    active: default
  redis:
    url: redis://192.168.9.205:6379
  session:
    store-type: redis
    redis:
      namespace: session:zlikun
